version: '3.8'

services:
  backend:
    build: ./backend
    image: threek8s-backend
    container_name: threek8s-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ~/.kube:/root/.kube:ro
    env_file:
      - ./backend/.env
    networks:
      - threek8s-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    image: threek8s-frontend
    container_name: threek8s-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - threek8s-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  threek8s-network:
    driver: bridge