{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "threek8s.fullname" . }}
  labels:
    {{- include "threek8s.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "threek8s.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- with .Values.networkPolicy.policyTypes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- else }}
  ingress:
    # Allow ingress from pods in the same namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
    # Allow ingress from ingress controller
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.frontend.service.targetPort }}
        - protocol: TCP
          port: {{ .Values.backend.service.targetPort }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- else }}
  egress:
    # Allow egress to Kubernetes API server
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow inter-service communication
    - to:
        - podSelector:
            matchLabels:
              {{- include "threek8s.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.backend.service.targetPort }}
  {{- end }}
{{- end }}