name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.service }}
        run: |
          docker build -t test-${{ matrix.service }}:${{ github.sha }} ./${{ matrix.service }}

      - name: Test ${{ matrix.service }} image
        if: matrix.service == 'backend'
        run: |
          # Basic smoke test - ensure container can start
          docker run --rm test-${{ matrix.service }}:${{ github.sha }} echo "Container started successfully"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: test-${{ matrix.service }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results-${{ matrix.service }}.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results-${{ matrix.service }}.sarif'
          category: 'container-${{ matrix.service }}'

  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Lint Helm chart
        run: |
          helm lint helm/threek8s/

      - name: Template Helm chart
        run: |
          helm template test-release helm/threek8s/ --debug

  validate-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate GitHub Actions workflows
        run: |
          for workflow in .github/workflows/*.yml; do
            echo "Validating $workflow"
            # Basic YAML validation
            python3 -c "import yaml; yaml.safe_load(open('$workflow'))"
          done

  security-scanning:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ matrix.service }}/package-lock.json

      - name: Install dependencies
        working-directory: ./${{ matrix.service }}
        run: npm ci

      - name: Run security linting
        working-directory: ./${{ matrix.service }}
        run: npm run lint:security

      - name: Run dependency audit
        working-directory: ./${{ matrix.service }}
        run: npm audit --audit-level=high